# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/google/uuid";
    fetch = {
      type = "git";
      url = "https://github.com/google/uuid";
      rev = "c2e93f3ae59f2904160ceaab466009f965df46d6";
      sha256 = "0zw8fvl6jqg0fmv6kmvhss0g4gkrbvgyvl2zgy5wdbdlgp4fja0h";
    };
  }
  {
    goPackagePath = "github.com/spf13/cobra";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/cobra";
      rev = "b80588d523ec50c7fee20218426cf2ff70920f06";
      sha256 = "0gl861bn6bb45ands4742xzaxdvl69r4an1v7cyfis7mc450j7lg";
    };
  }
  {
    goPackagePath = "github.com/spf13/pflag";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/pflag";
      rev = "972238283c0625cf3e881de7699ba8f2524c340a";
      sha256 = "194h0lq3s27wcxcgahjl350x46v116x81zgkgh98q9v5iydig28l";
    };
  }
  {
    goPackagePath = "golang.org/x/crypto";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/crypto";
      rev = "9756ffdc24725223350eb3266ffb92590d28f278";
      sha256 = "0q7hxaaq6lp0v8qqzifvysl47z5rfdlrxkh3d29vsl3wyby3dxl8";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "9109b7679e13aa34a54834cfb4949cac4b96e576";
      sha256 = "169sg6fyjkykiylrgxr0pynv2zc3frkgssbsk5w2lqyl8mb319hl";
    };
  }
]
